nodeLinker: 'node-modules'

npmScopes:
  ida:
    npmRegistryServer: 'https://www.myget.org/F/ida-package-feed/npm/'
  figurine:
    npmRegistryServer: 'https://www.myget.org/F/ida-package-feed/npm/'

yarnPath: .yarn/releases/yarn-3.5.0.cjs

